### PR TITLE
binary file saving / loading utils + spikeglx quickstart script

### PR DESCRIPTION
**Pull request by jbmelander**
added functions to save and load (permanently) the recording object, in case multiple ms5 runs are needed

added quickstart script for running ms5 on spikeglx-acquired neuropixel data

### CODE REVIEW

**Comment by magland** [comment]
Excellent, thank you!

@jbmelander could you do me a favor and update your branch to catch up to the upstream? It shows it is 8 commits behind. I think there should be a button to do that on gh.

**Comment by jbmelander** [comment]
OK @magland 
I updated the main branch on my fork. You should see the quickstart in examples and the new load/save utilities in mountainsort5/utils/

**Comment by magland** [comment]
@jbmelander 

I made some adjustments to keep my linter (pyright) happy, for the CI

https://github.com/flatironinstitute/mountainsort5/blob/main/examples/neuropixel_quickstart/spikeglx.py

**Comment by jbmelander** [comment]
Beautiful. Thanks, Jeremy.

**Comment by jbmelander** [comment]
Should I add a link to the quick start in the README?

**Comment by magland** [comment]
Yes, please do.

**Pull request merged**
